### ISSUE TITLE
MCM doesn't find a show on tvdb if it's the only one found

### ISSUE THREAD

**Issue by manuliege** [psouza4/mediacentermaster#1761] opened 2017-02-19 23:29 UTC
I'm migrating my whole tv collection to MCM because of its capabilities to mass rename easely.
I have around 500 tv shows.
About 5% (25 on 500 so) weren't recognized by MCM by using thetvdb scraper.
The name of my folders are exactly the same as the names of the tv shows on tvdb : if tvdb has a "(US)", "(2014)", ... or whatever at the end of the title, i have it too as name of my folder.
So i tried to search manually on the tvdb website (field "search" above), by typing exactly the name of my folder, and i saw that all the tv shows that failed to be recognized are tv shows that tvdb finds immediately via the name ; i mean it's the one & only show found.
So the webpage of this tv show appears immediately, and no list to choose a tv show as usually.

Maybe thta's the problem ?

**Comment by Happy2Play** [comment] 2017-02-22 02:49
You would need to provide specific examples.  I haven't seen any issues like this but I haven't started from scratch in awhile, but I can setup a test library to see if I can replicate this.

All issues should be brought up in the forum to troubleshoot first.

**Comment by psouza4** [comment] 2017-04-12 01:25
Unable to reproduce and no further updates, closing this issue.

**Closed by psouza4** 2017-04-12 01:25 UTC
