### ISSUE TITLE
T.T.Y in organisation does not work.

### ISSUE THREAD

**Issue by Stormtraxx** [psouza4/mediacentermaster#1736] opened 2016-03-08 14:51 UTC
![2016-03-08 15_42_48-search](https://cloud.githubusercontent.com/assets/17725924/13604924/79a6e808-e545-11e5-8937-68b53e06d5d2.png)

**Comment by Happy2Play** [comment] 2016-03-08 19:11
Please open a topic the forum with your Support Information and a debug log of the issue.  Was unable o reproduce by changing token and renaming or fetching, didn't try parser.

**Comment by psouza4** [comment] 2017-04-12 01:28
Unable to reproduce and no further updates to this issue; closing this issue.

**Closed by psouza4** 2017-04-12 01:28 UTC
